/**
 * Pipeline composer for v2.
 *
 * Phase 1 scope: takes a fixed Recipe (NOT generated by LLM —
 * loaded from canonical-recipes.json) and a date range, runs
 * stages 4 and 5 (scoring + ranking), produces a TraceRecord.
 *
 * Stages 1 (parse-intent) and 3 (build-recipe) require LLM wiring
 * and ship in a follow-up commit. The trace structure already
 * accommodates them — they're just left empty for now.
 */

import type { IEphemerisCalculator } from '../../../core/ephemeris/interface';
import type { Recipe, Predicate } from '../schema/dsl';
import type { TraceRecord, StageDateRange } from '../schema/trace';
import type { AspectPerfection } from '../predicates/types';
import { TraceRecorder } from '../trace/recorder';
import { TraceStore } from '../trace/store';
import { buildDayContext, dateRangeISO } from './build-day-context';
import { scoreDay } from './score-day';
import { rankWindows, type RankInput } from './rank-windows';

export interface FindWithFixedRecipeArgs {
    /** Original user prompt — recorded in trace for analytics, not used to compute. */
    user_prompt: string;
    user_id?: string | null;
    /** Already-validated Recipe (from canonical-recipes.json or hand-built). */
    recipe: Recipe;
    /** ISO YYYY-MM-DD */
    start_date: string;
    end_date: string;
    location: { latitude: number; longitude: number; timezone: string };
    top_n?: number;
    debug_mode?: boolean;
}

export interface FindResult {
    trace: TraceRecord;
    windows: TraceRecord['stage_scoring']['scored_days']; // ranked survivors
}

/**
 * Run scoring + ranking against a fixed recipe over a date range.
 * Persists the trace before returning.
 */
export async function findWithFixedRecipe(
    args: FindWithFixedRecipeArgs,
    deps: { ephemeris: IEphemerisCalculator; traceStore: TraceStore },
): Promise<FindResult> {
    const recorder = new TraceRecorder({
        user_prompt: args.user_prompt,
        user_id: args.user_id ?? null,
        debug_mode: args.debug_mode ?? false,
    });

    // Stage 1: skipped (LLM not wired in phase 1). Record placeholder.
    recorder.recordIntentEnvelope({
        model: 'fixed-recipe-no-llm',
        provider: 'mock',
        prompt_template_version: 'n/a',
        latency_ms: 0,
        cost_usd: 0,
        input_tokens: 0,
        output_tokens: 0,
        cache_hit: false,
        output: {
            activity: '(fixed recipe)',
            location: args.location.timezone,
            date_hint: { raw_phrase: null, approximate_start: null, approximate_end: null },
            constraints: [],
            confidence: 1,
        },
    });

    // Stage 2: date range as supplied.
    const dateStage: StageDateRange = {
        method: 'default_30d',
        extracted: false,
        start: args.start_date,
        end: args.end_date,
        raw_phrase: null,
    };
    recorder.recordDateRange(dateStage);

    // Stage 3: skipped. Record the fixed recipe as if LLM produced it.
    recorder.recordRecipe({
        model: 'fixed-recipe-no-llm',
        provider: 'mock',
        prompt_template_version: 'n/a',
        latency_ms: 0,
        cost_usd: 0,
        input_tokens: 0,
        output_tokens: 0,
        cache_hit: false,
        output: args.recipe,
    });

    // Stages 4-5: scoring + ranking.
    try {
        const dates = dateRangeISO(args.start_date, args.end_date);

        // Pre-fetch aspect perfections for the entire window (one HTTP
        // call). The recipe's `applying:true` predicates with the default
        // `perfects_in_day` semantic look these up day-by-day.
        const perfections = await fetchPerfectionsForRecipe(
            args.recipe,
            args.start_date,
            args.end_date,
            deps.ephemeris,
        );

        const inputs: RankInput[] = [];

        // Score serially in chunks to avoid hammering the ephemeris.
        const CHUNK = 5;
        for (let i = 0; i < dates.length; i += CHUNK) {
            const chunk = dates.slice(i, i + CHUNK);
            const chunkResults = await Promise.all(
                chunk.map(async (date) => {
                    const ctx = await buildDayContext(date, {
                        ephemeris: deps.ephemeris,
                        location: args.location,
                        perfections,
                    });
                    return scoreDay(args.recipe, ctx);
                }),
            );
            for (const r of chunkResults) {
                inputs.push({
                    scored: r.scored,
                    disqualified: r.disqualified,
                    disqualificationReasons: r.disqualificationReasons,
                });
            }
        }

        const ranked = rankWindows(inputs, { topN: args.top_n ?? 10 });
        recorder.recordScoring(ranked.stage_scoring);
        recorder.recordOutput(ranked.stage_output);

        const trace = recorder.build();
        await deps.traceStore.append(trace);
        return { trace, windows: ranked.windows };
    } catch (e) {
        recorder.recordError('scoring', e);
        const trace = recorder.build();
        // best-effort persist even on failure
        try { await deps.traceStore.append(trace); } catch { /* swallow */ }
        throw e;
    }
}

/**
 * Walk the recipe's predicates, collect every (pair, aspect-types)
 * tuple whose predicate uses applying:true with the default
 * 'perfects_in_day' window, and pre-fetch all perfections for the
 * full query window in a single ephemeris call.
 *
 * Returns an empty list if no such predicate exists — the API call is
 * skipped entirely in that case (most recipes that don't ask for
 * applying:true incur zero cost from this stage).
 */
async function fetchPerfectionsForRecipe(
    recipe: Recipe,
    startDate: string,
    endDate: string,
    ephemeris: IEphemerisCalculator,
): Promise<AspectPerfection[]> {
    const pairsSet = new Set<string>();
    const aspectsSet = new Set<string>();

    const collect = (pred: Predicate): void => {
        if (pred.type !== 'aspect') return;
        if (pred.applying !== true) return;
        const window = pred.window ?? 'perfects_in_day';
        if (window !== 'perfects_in_day') return;
        // Canonicalize the pair: sorted alphabetically so reverse pairs
        // collide in the set. Order-independent for the API.
        const pair = [pred.from, pred.to].sort().join('|');
        pairsSet.add(pair);
        for (const a of pred.aspects) aspectsSet.add(a);
    };
    for (const d of recipe.disqualifiers) collect(d);
    for (const wc of recipe.weighted_conditions) collect(wc.predicate);

    if (pairsSet.size === 0 || aspectsSet.size === 0) return [];

    const pairs: ReadonlyArray<readonly [string, string]> = [...pairsSet]
        .map((s) => s.split('|') as [string, string]);
    const aspects = [...aspectsSet];

    // The endpoint expects ISO 8601 timestamps. Use [start_date 00:00, end_date+1 00:00) UTC
    // so the inclusive day range maps to a half-open instant range.
    const startISO = `${startDate}T00:00:00Z`;
    const endISO = new Date(`${endDate}T00:00:00Z`).getTime() + 24 * 60 * 60 * 1000;
    const endISOStr = new Date(endISO).toISOString();

    const resp = await ephemeris.getAspectPerfections(startISO, endISOStr, pairs, aspects);

    return resp.perfections.map((p) => ({
        from: p.planet_a as AspectPerfection['from'],
        to: p.planet_b as AspectPerfection['to'],
        type: p.aspect as AspectPerfection['type'],
        exactAt: new Date(p.exact_at),
    }));
}

/**
 * Helper: load a canonical recipe by id from the bundled JSON.
 */
export function loadCanonicalRecipe(
    id: 'business_launch' | 'marriage_relationship' | 'mercury_matters' | 'mars_matters' | 'jupiter_matters',
): Recipe {
    // Loaded lazily via require so tests/scripts can mock if needed.
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const data = require('../prompts/examples/canonical-recipes.json') as {
        recipes: Array<Record<string, unknown> & { _id: string }>;
    };
    const found = data.recipes.find((r) => r._id === id);
    if (!found) throw new Error(`Canonical recipe not found: ${id}`);
    // Strip leading-underscore meta keys before returning.
    const cleaned: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(found)) {
        if (!k.startsWith('_')) cleaned[k] = v;
    }
    return cleaned as Recipe;
}
